site_name: CODA RC Web
site_dir: https://michaellhommetransdev.github.io/demo-spec/
docs_dir: ./docs
theme:
  name: 'material'
  features:
    - content.code.copy
    
markdown_extensions:
  - def_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format